version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
  backend:
    image: higoods2023/higoods-api:0.0.3
    container_name: backend
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: awslogs
      options:
        awslogs-group: higoods-docker-log
        awslogs-region: ap-northeast-2
        awslogs-stream: backend
#  front:
#      image: david0218/higoods-frontend:dev
#      container_name: front
#      network_mode: "host"
#      environment:
#        - TZ=Asia/Seoul
#  admin:
#      image: david0218/higoods-admin:dev
#      container_name: admin
#      network_mode: "host"
#      environment:
#        - TZ=Asia/Seoul
  nginx:
      network_mode: "host"
      depends_on:
        - backend
#        - front
#        - admin
      restart: always
      image: higoods2023/higoods-nginx:1.0.1
      environment:
        - TZ=Asia/Seoul
